name: Build
on:
  push:
    branches:
      - main
jobs:
  docker_build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build and push go project
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: muslim1985/go-project:latest

#      - name: Build and push nginx
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./example-app/Dockerfile
#          push: true
#          tags: akimmalidocker/nginx:latest

#  deploy_to_server:
#    needs: docker_build
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: executing remote ssh commands using ssh key
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SHOP_SERVER }}
#          port: ${{ secrets.PORT }}
#          script: |
#            docker-compose stop
#            docker-compose rm -f
#            docker-compose pull
#            docker-compose up --build -d
#            docker-compose run --rm -w /var/www/example-app app php artisan migrate
#            docker cp app:/var/www  work