name: Build
on:
  push:
    branches:
      - main
jobs:
  docker_build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build and push go project
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: muslim1985/go-project:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-22-11-do-0-ams3-1657563434881

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Lint helm charts
        run: helm lint k8s/mychart

      - name: Deploy
        run: |
          helm upgrade --install my-chart k8s/mychart



#  deploy_to_server:
#    needs: docker_build
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: executing remote ssh commands using ssh key
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SHOP_SERVER }}
#          port: ${{ secrets.PORT }}
#          script: |
#            docker-compose stop
#            docker-compose rm -f
#            docker-compose pull
#            docker-compose up --build -d
#            docker-compose run --rm -w /var/www/example-app app php artisan migrate
#            docker cp app:/var/www  work